import { Geist, Geist_Mono } from "next/font/google";

import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: { title: string; description: string } = {
  title: "Video Calling welcomes",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function Rl({ children }: RootLayoutProps) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}>
          
          {children}
    </div>
  );
}
