import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: { title: string; description: string } = {
  title: "Video Calling welcomes",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function Ro({ children }: RootLayoutProps) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}>
      <SidebarProvider>
        <AppSidebar />
        <main>
          <SidebarTrigger />
          {children}
        </main>
      </SidebarProvider>
    </div>
  );
}
