import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { SocketProvider } from "@/providers/socket";
import { PeerProvider } from "@/providers/Peer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Video Calling welcomes",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const l: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}>
      
      <SocketProvider>
        <PeerProvider>
      {children}
      </PeerProvider>
      </SocketProvider>
    </div>
  );
};

export default l;
