import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Video Calling welcomes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}
      >
       
        {children}
     

        
      </div>

  );
}
